server:
  address: 0.0.0.0

spring:
  application:
    name: app

  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app?serverTimezone=Asia/Seoul
    username: app
    password: app

  # JPA
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.hibernate.format_sql: true
    show-sql: true
